name: Rust CI

on:
  push:
    paths:
      - 'rust/**'
      - '.github/workflows/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: rust/runtime/
    - name: Run tests
      run: cargo test --verbose
      working-directory: rust/runtime/
  benchmark:
    name: benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Run Benchmarks
      run: cargo bench
      working-directory: rust/runtime/
  tpch:
    name: tpch-test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Run tpch queries
      run: RUST_LOG=info cargo run --release --example tpch -- q1
      working-directory: rust/runtime/
