name: Rust CI

on:
  push:
    paths:
      - 'rust/*'
      - '.github/workflows/*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - working-directory: rust/
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
