name: Rust CI

on:
  push:
    paths:
      - 'rust/**'
      - '.github/workflows/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Benchmark
      run: cargo bench
      working-directory: rust/runtime/
